name: celest_analyzer_plugin
description: A plugin for the Dart analyzer that provides support for Celest backends.
publish_to: none

environment: 
  sdk: ^3.5.0

dependencies: 
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0
  collection: ^1.18.0
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  source_span: ^1.10.0
  stack_trace: ^1.12.0
  yaml: ^3.1.2

dev_dependencies:
  test: any
  lints: ^6.0.0
