name: celest_auth
description: The Auth runtime and client library for Celest, the Flutter cloud platform.
version: 0.4.0-dev.2
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/packages/celest_auth

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.11.0
  built_collection: ^5.1.1
  built_value: ^8.9.1
  cedar: ^0.1.0
  celest_core: ^0.4.0-0
  chunked_stream: ^1.4.2
  corks_cedar: ^0.1.0
  ffi: ^2.1.2
  http: ^1.2.1
  logging: ^1.2.0
  meta: ^1.9.0
  os_detect: ^2.0.1
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  checks: ^0.3.0
  lints: ">=3.0.0 <5.0.0"
  test: ^1.25.1
