name: libcoder
description: A general-purpose serialization framework for Dart.
repository: https://github.com/celest-dev/celest/tree/main/packages/coder
version: 0.0.1

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
