name: celest_core
description: Celest types and utilities shared between the client and the cloud.
version: 0.2.1
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/packages/celest_core

environment:
  sdk: ^3.3.0

dependencies:
  collection: ^1.18.0
  http: ">=0.13.0 <2.0.0"
  ffi: ^2.1.2
  jni: ^0.7.2
  meta: ^1.10.0
  os_detect: ^2.0.1
  path: ^1.9.0
  win32: ^5.2.0

dev_dependencies:
  # TODO(dnys1): Use ^12.0.0 when released
  # Needed to support global fields.
  ffigen:
    git:
      url: https://github.com/dart-lang/native
      path: pkgs/ffigen
  jnigen: ^0.7.0
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
