name: celest_cloud_core
description: Core types and utilities for Celest Cloud services.
version: 0.1.1
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/services/celest_cloud_core

environment:
  sdk: ^3.5.0
resolution: workspace

dependencies:
  cedar: ^0.2.6
  celest_cloud: ^0.1.8
  celest_core: ^1.0.0
  collection: ^1.18.0
  drift: ^2.27.0
  fixnum: ^1.0.0
  meta: ^1.16.0
  petitparser: ^6.0.0

dev_dependencies:
  celest_lints: ^1.0.0
  checks: ^0.3.0
  test: ^1.24.0
