name: celest
description: The Flutter cloud platform. Celest enables you to build your entire backend in Dart.
version: 0.4.0-dev.2
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/packages/celest

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.11.0
  celest_auth: ^0.4.0-0
  celest_core: ^0.4.0-0
  chunked_stream: ^1.4.2
  meta: ^1.11.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.1
