name: celest
description: The Flutter cloud platform. Celest enables you to build your entire backend in Dart.
version: 1.0.1+1
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/packages/celest

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  async: ^2.11.0
  celest_ast: ^0.1.0
  celest_auth: ^1.0.0
  celest_cloud: ^0.1.1
  celest_core: ^1.0.0
  chunked_stream: ^1.4.2
  cloud_http: ^0.1.0
  collection: ^1.18.0
  convert: ^3.1.1
  crypto_keys: ^0.3.0
  drift: ^2.21.0
  drift_hrana: ^1.0.2
  file: ^7.0.1
  fixnum: ^1.1.0
  google_cloud: ^0.2.0
  http: ^1.0.0
  http_parser: ^4.0.0
  http_sfv: ^0.1.0
  logging: ^1.2.0
  meta: ^1.11.0
  path: ^1.9.0
  platform: ^3.1.5
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  sqlite3: ^2.4.6
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  web_socket_channel: ^3.0.0
  x509: ^0.2.4

dev_dependencies:
  build_runner: ^2.4.13
  celest_lints:
    path: ../celest_lints
  drift_dev: ^2.21.0
  process: ^5.0.2
  pub_semver: ^2.1.4
  stream_transform: ^2.1.0
  test: ^1.25.1
  web: '>=0.5.0 <2.0.0'
