name: celest_ast
description: A structured representation of Celest project and service definitions.
version: 0.1.6
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/packages/celest_ast

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.2
  cedar: ^0.2.2
  code_builder: ^4.10.0
  collection: ^1.18.0
  fixnum: ^1.1.0
  path: ^1.9.0
  protobuf: ^3.1.0
  pub_semver: ^2.1.4
  recase: ^4.1.0
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.12
  built_value_generator: ^8.9.2
  celest_lints: ^1.1.0
  test: ^1.24.0
