name: celest_backend
description: The Celest backend for example.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  celest: ^0.2.0
  celest_core: ^0.2.0
  http: ">=0.13.0 <2.0.0"

dependency_overrides:
  celest:
    path: ../../
  celest_core:
    path: ../../../celest_core

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
