name: celest_cli
description: The command-line interface for Celest.
version: 1.0.6+2
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  # TODO: Cannot use latest because type system uses `identical` in subtype checks instead of `==`
  # https://github.com/dart-lang/sdk/commit/f82ab4c6eaf0ebb6f3e85de6ce323b04250be700
  analyzer: <6.5.0
  analyzer_plugin: ^0.11.3
  archive: ^3.4.9
  args: ^2.4.2
  async: ^2.11.0
  built_collection: ^5.1.1
  built_value: ^8.6.3
  cedar:
    path: ../../cedar/packages/cedar
  celest:
    path: ../../celest/packages/celest
  celest_ast:
    path: ../../celest/packages/celest_ast
  celest_auth:
    path: ../../celest/packages/celest_auth
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_cloud:
    path: ../../celest/packages/celest_cloud
  celest_core:
    path: ../../celest/packages/celest_core
  chunked_stream: ^1.4.2
  cli_script: ^1.0.0
  code_builder: ^4.8.0
  collection: ^1.18.0
  convert: ^3.1.1
  corks_cedar: ^0.2.1
  crypto: ^3.0.3
  dart_style: ^2.3.4
  dcli: ^6.0.5
  dcli_terminal: ^6.0.3
  drift: ">=2.21.0 <2.22.0"
  email_validator: ^3.0.0
  file: ^7.0.0
  fixnum: ^1.1.0
  functions_framework: ^0.4.3+1
  git: ^2.3.0
  graphs: ^2.3.2
  html2md: ^1.3.1
  http: ^1.1.2
  http_parser: ^4.0.2
  intl: ^0.19.0
  io: ^1.0.4
  json_annotation: ^4.9.0
  lib_openapi:
    path: ../../packages/lib_openapi
  libcoder: ^0.0.1
  logging: ^1.2.0
  mason_logger: ^0.3.0
  meta: ^1.10.0
  native_assets_builder: ^0.8.1
  native_assets_cli: ^0.7.2
  native_storage: ^0.2.2
  os_detect: ^2.0.1
  package_config: ^2.1.0
  path: ^1.8.3
  platform: ^3.1.3
  pool: ^1.5.1
  process: ^5.0.1
  protobuf: ^3.1.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  sentry: ^8.5.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^2.0.0
  source_span: ^1.10.0
  sqlite3: ^2.4.6
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  stream_transform: ^2.1.0
  toml: ^0.16.0
  vm_service: ^15.0.0
  watcher: ^1.1.0
  yaml: ^3.1.2
  # TODO: 2.2.2 breaks sorting of edits
  yaml_edit: 2.2.1

dependency_overrides:
  cedar:
    path: ../../cedar/packages/cedar
  celest:
    path: ../../celest/packages/celest
  celest_ast:
    path: ../../celest/packages/celest_ast
  celest_auth:
    path: ../../celest/packages/celest_auth
  celest_cli_common:
    path: ../../packages/celest_cli_common
  celest_cloud:
    path: ../../celest/packages/celest_cloud
  celest_core:
    path: ../../celest/packages/celest_core

dev_dependencies:
  benchmark_harness: ^2.2.2
  build: ^2.4.1
  build_runner: ^2.4.7
  build_test: ^2.2.1
  built_value_generator: ^8.8.0
  celest_lints:
    path: ../../packages/celest_lints
  checks: ^0.3.0
  dart_jsonwebtoken: ^3.1.1
  drift_dev: ">=2.21.0 <2.22.0"
  gcloud: ^0.8.13
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  jose: ^0.3.4
  json_serializable: ^6.8.0
  mocktail: ^1.0.2
  mustache_template: ^2.0.0
  test: ^1.24.9
  test_descriptor: ^2.0.1

executables:
  celest:
