name: celest_cli
description: The command-line interface for Celest.
version: 1.0.14
homepage: https://celest.dev
repository: https://github.com/celest-dev/celest/tree/main/apps/cli

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  analyzer: ^7.4.0
  analyzer_plugin: ^0.13.0
  archive: ^4.0.4
  args: ^2.4.2
  async: ^2.11.0
  built_collection: ^5.1.1
  built_value: ^8.9.5
  cedar: ^0.2.6
  celest: ^1.0.0
  celest_ast: ^0.1.4
  celest_auth: ^1.0.0
  celest_cloud: ^0.1.10
  celest_cloud_auth: ^0.3.5
  celest_cloud_core: ^0.1.1
  celest_core: ^1.0.0
  chunked_stream: ^1.4.2
  cli_script: ^1.0.0
  cli_util: ^0.4.2
  code_builder: ^4.8.0
  collection: ^1.18.0
  convert: ^3.1.1
  corks_cedar: ^0.2.4
  crypto: ^3.0.3
  dart_console: ^4.1.1
  dart_style: ^3.0.0
  dcli: ^7.0.1
  dcli_terminal: ^7.0.1
  drift: '>=2.27.0 <2.29.0'
  email_validator: ^3.0.0
  ffi: ^2.1.4
  file: ^7.0.0
  fixnum: ^1.1.0
  functions_framework: ^0.4.3+1
  git: ^2.3.0
  graphs: ^2.3.2
  html2md: ^1.3.1
  http: ^1.1.2
  http_parser: ^4.0.2
  intl: ^0.20.2
  io: ^1.0.4
  json_annotation: ^4.9.0
  libcoder: ^0.0.1
  logging: ^1.2.0
  mason_logger: ^0.3.0
  meta: ^1.10.0
  mustache_template: ^2.0.0
  native_storage: ^0.3.0
  os_detect: ^2.0.1
  package_config: ^2.1.0
  path: ^1.8.3
  platform: ^3.1.3
  pool: ^1.5.1
  process: ^5.0.1
  protobuf: ^4.0.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  sentry: ^9.1.0
  sentry_logging: ^9.1.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ">=2.0.0 <4.0.0"
  source_span: ^1.10.0
  sqlite3: ^2.4.6
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  stream_transform: ^2.1.0
  timing: ^1.0.2
  toml: ^0.16.0
  uuid: ^4.5.1
  vm_service: ^15.0.0
  watcher: ^1.1.0
  win32: ^5.11.0
  yaml: ^3.1.2
  # TODO: 2.2.2 breaks sorting of edits
  yaml_edit: 2.2.1

dev_dependencies:
  benchmark_harness: ^2.2.2
  build: ^3.0.0
  build_runner: ^2.7.0
  build_test: ^3.2.2
  built_value_generator: ^8.9.4
  celest_lints:
    path: ../../packages/celest_lints
  celest_test: ^0.1.0
  checks: ^0.3.0
  dart_jsonwebtoken: ^3.1.1
  drift_dev: '>=2.27.0 <2.29.0'
  gcloud: ^0.8.13
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  jose: ^0.3.4
  json_serializable: ^6.8.0
  mocktail: ^1.0.2
  test: ^1.26.0
  test_descriptor: ^2.0.1

executables:
  celest:
