name: cedar_ffi
on:
  pull_request:
    paths:
      - ".github/workflows/cedar_ffi.yaml"
      - "packages/cedar_ffi/**"
      - "packages/cedar_ffi/third_party/cedar"
      - "packages/cedar_ffi/third_party/cedar/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-latest
    runs-on: ${{ matrix.os }}
    # TODO(dnys1): Speed up Rust builds
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3 # main
      # Will often be out-of-date on runners
      - name: Setup Rust
        run: rustup update stable && rustup default stable
      - name: Get Packages
        working-directory: packages/cedar_ffi
        run: dart pub get
      - name: Test
        working-directory: packages/cedar_ffi
        run: dart --enable-experiment=native-assets test --fail-fast
